spring:
  kafka:
    bootstrap-servers: localhost:9092

app:
  kafka:
    topicToRead: order-status-service
    topicToWrite: order-topic
    kafkaMessageGroupId: "kafka-message-group-id"
server:
  port: 8080